baseURL: "https://wondrous-swan-ff47f7.netlify.app"
languageCode: en-us
title: Ruyun's Blog # here changes the title of the webpage
theme: PaperMod

params:
  homeInfoParams: 
    title: "hello Stranger"
    Content: Welcome to my blog. Let me test if this message is syncs
  # socialIcons:
  #   -name: facebook
  #     url: "https://facebook.com/"
  #   -name: twitter
  #     url: "https://www.google.com/"
  #   -name: github
  #     url: "https://www.google.com/"


  ShowBreadCrumbs: true
  ShowShareButtons: true
  ShowPostNavLinks: true

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30